CLean all-state-population file

In [41]:
import pandas as pd
df_population=pd.read_excel("population.xlsx",header=[1],skiprows=[0,1,-1])
df_population=df_population.rename(columns = {'Unnamed: 0':'state',2019:'2019population'})
df_population=df_population[['state', '2019population']].dropna()
df_population

                    state  2019population
0           United States     328239523.0
1               Northeast      55982803.0
2                 Midwest      68329004.0
3                   South     125580448.0
4                    West      78347268.0
5                .Alabama       4903185.0
6                 .Alaska        731545.0
7                .Arizona       7278717.0
8               .Arkansas       3017804.0
9             .California      39512223.0
10              .Colorado       5758736.0
11           .Connecticut       3565287.0
12              .Delaware        973764.0
13  .District of Columbia        705749.0
14               .Florida      21477737.0
15               .Georgia      10617423.0
16                .Hawaii       1415872.0
17                 .Idaho       1787065.0
18              .Illinois      12671821.0
19               .Indiana       6732219.0
20                  .Iowa       3155070.0
21                .Kansas       2913314.0
22              .Kentucky       4467673.0
23             .Louisiana       4648794.0
24                 .Maine       1344212.0
25              .Maryland       6045680.0
26         .Massachusetts       6892503.0
27              .Michigan       9986857.0
28             .Minnesota       5639632.0
29           .Mississippi       2976149.0
30              .Missouri       6137428.0
31               .Montana       1068778.0
32              .Nebraska       1934408.0
33                .Nevada       3080156.0
34         .New Hampshire       1359711.0
35            .New Jersey       8882190.0
36            .New Mexico       2096829.0
37              .New York      19453561.0
38        .North Carolina      10488084.0
39          .North Dakota        762062.0
40                  .Ohio      11689100.0
41              .Oklahoma       3956971.0
42                .Oregon       4217737.0
43          .Pennsylvania      12801989.0
44          .Rhode Island       1059361.0
45        .South Carolina       5148714.0
46          .South Dakota        884659.0
47             .Tennessee       6829174.0
48                 .Texas      28995881.0
49                  .Utah       3205958.0
50               .Vermont        623989.0
51              .Virginia       8535519.0
52            .Washington       7614893.0
53         .West Virginia       1792147.0
54             .Wisconsin       5822434.0
55               .Wyoming        578759.0
57            Puerto Rico       3193694.0